config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  default_url_options host: "localhost:3000"
  root "books#index"
  get "users/show"
  get "users/new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  delete "logout", to: "sessions#destroy"

  resources :users, :authors, :publishers, :books, :categories, :borrows
  resources :borrow_details, only: [:create, :update, :destroy]
  #resource :cart, only: [:show]
  resource :cart
  resources :cart

  namespace :admin do
    resources :books
    resources :borrows do
      member do
        get "accept_request"
        patch "deny_request"
      end
    end
    resources :borrow_details, only: [:create, :update, :destroy]
  end

  resources :books do
    resources :likes
    resources :comments
  end

  resources :users do
    resources :likes
    resources :comments
  end
end

app/models/book.rb
class Book < ApplicationRecord
  VALID_NUMBER_REGEX = /\A\d+\z/i

  has_many :likes, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :borrow_details, dependent: :destroy
  belongs_to :publisher
  belongs_to :category
  belongs_to :author

  delegate :name, to: :category, prefix: :category

  validates :name, presence: true,
    length: { maximum: Settings.book.name_maximum }
  validates :num_of_pages, presence: true,
    length: {minimum: Settings.book.number.min_length}
  validates :image, presence: true
  validates :amount, format: { with: VALID_NUMBER_REGEX},
    length: {minimum: Settings.book.number.min_length}

  scope :alphabet, ->{order name: :ASC}
  scope :_page,->(page){paginate page: page, per_page: Settings.paginate.per_page}
  scope :search_book, -> search {
    where("books.name LIKE ?", "%#{search.strip}%") if search.present?
  }

  mount_uploader :image, PictureUploader

  def liked_by? user
    likes.liked_by(user.id).present?
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  include BooksHelper
  before_action :load_book, except: %i(new create index)

  authorize_resource

  def new
    @book = Book.new
  end

  def create
    @book = Book.new books_params
    if @book.save
      flash[:success] = t ".success_message"
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit; end

  def destroy
    if @book.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to admin_books_path
  end

  def index
    @search = Book.ransack (params[:q])
    @books = @search.result.alphabet.paginate page: params[:page],per_page: Settings.book.per_page
    #new khong tao ra relationship nhung build thi yes
    @borrow_detail = current_borrow.borrow_details.build
  end

  def update
    if @book.update_attributes books_params
      flash[:success] = t ".update_success"
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  private
  def books_params
    params.require(:book).permit :name, :description, :num_of_pages, :image,
      :amount, :author_id, :category_id, :publisher_id
  end

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "books.load_book.error_message"
    redirect_to root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper

  before_action :load_book, only: :show

  authorize_resource

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @search = Book.ransack (params[:q])
    @books = @search.result.alphabet.paginate page: params[:page],per_page: Settings.book.per_page
    @borrow_detail = current_borrow.borrow_details.build
  end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "books.load_book.error_message"
    redirect_to root_path
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def get_authors name
    Author.order(name)
  end

  def get_categories name
    Category.order(name)
  end

  def get_publishers name
    Publisher.order(name)
  end
end

app/views/admin/books/_book.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <tr>
        <td class="text-justify" width="20%"><%= link_to book.name, book %></td>
        <td class="text-justify" width="15%"><%= link_to book.category.name, book %></td>
        <td class="text-center" width="20%"><%= book.author.name %></td>
        <td class="text-center" width="20%"><%= book.publisher.name %></td>
        <td class="text-center" width="10%"><%= book.amount %></td>
        <% if current_user.admin? %>
          <td class="text-right">
            <%= link_to t(".delete"), admin_book_path(book), method: :delete,
            data: {confirm: t(".confirm")} %>
            | <%= link_to t(".edit"), edit_admin_book_path(book) %>
          </td>
        <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/admin/books/_form.html.erb
<%= form_for @book, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: @book%>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :number_of_pages %>
  <%= f.number_field :num_of_pages, class: "form-control" %>

  <%= f.label :image %>
  <%= f.file_field :image, accept: "image/png,image/jpeg", class: "form-control" %>

  <%= f.label :amount %>
  <%= f.number_field :amount, class: "form-control" %>

  <%= f.label :authors %>
  <%= f.collection_select :author_id, get_authors(:name), :id, :name, include_blank: false %>

  <%= f.label :categories %>
  <%= f.collection_select :category_id, get_categories(:name), :id, :name, include_blank: false %>

  <%= f.label :publishers %>
  <%= f.collection_select :publisher_id, get_publishers(:name), :id, :name, include_blank: false %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".update") %>
<% provide(:url, admin_book_path) %>
<h1><%= t (".title") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".title") %></h1><hr>
<%= link_to new_admin_book_path, class: "btn btn-danger" do %>
  <span class="glyphicon glyphicon-plus">&nbsp;<%= t(".new") %></span>
<% end %>
<hr>
<div class="input-group search_inline">
  <%= search_form_for  @search, url: admin_books_path do |f| %>
      <%= f.text_field :name_cont,
    placeholder: t(".search"), class: "form-control search_input" %>
      <%= f.submit t(".button_search"), class: "btn btn-primary btn_search"%>
  <% end %>
</div><hr>
<%= will_paginate %>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th class="text-justify active" width="20%"><%= sort_link(@search, :name, t(".name")) %></th>
          <th class="text-justify active" width="15%"><%= sort_link(@search, :category_id, t(".category")) %></th>
          <th class="text-center active" width="20%"><%= sort_link(@search, :author_id, t(".author")) %></th>
          <th class="text-center active" width="19%"><%= sort_link(@search, :publisher_id, t(".publisher")) %></th>
          <th class="text-center active" width="12%"><%= sort_link(@search, :amount, t(".amount")) %></th>
          <% if current_user.admin? %>
            <th class="text-right active"><%= t ".action" %></th>
          <% end %>
        </tr>
      </thead>
    </table>
  </div>
</div>
<%= render @books %>
<%= will_paginate %>

app/views/admin/books/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create") %>
<% provide(:url, admin_books_path) %>
<h1><%= t(".title") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>