config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  default_url_options host: "localhost:3000"
  root "books#index"
  get "users/show"
  get "users/new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  delete "logout", to: "sessions#destroy"

  resources :users, :authors, :publishers, :books, :categories, :borrows
  resources :borrow_details, only: [:create, :update, :destroy]
  #resource :cart, only: [:show]
  resource :cart
  resources :cart

  namespace :admin do
    resources :books
    resources :borrows do
      member do
        get "accept_request"
        patch "deny_request"
      end
    end
    resources :borrow_details, only: [:create, :update, :destroy]
  end

  resources :books do
    resources :likes
    resources :comments
  end

  resources :users do
    resources :likes
    resources :comments
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :follows, dependent: :destroy
  validates :name, presence: true,
    length: { maximum: Settings.author.name_maximum }
  scope :alphabet, ->{order name: :ASC}
  scope :search_author, -> search {
    where("authors.name LIKE ?", "%#{search.strip}%") if search.present?
  }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author, except: %i(new create index)

  authorize_resource

  def new
    @author = Author.new
  end

  def create
    @author = Author.new authors_params
    if @author.save
      flash[:success] = t ".success_message"
      redirect_to authors_path
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit; end

  def destroy
    if @author.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to authors_path
  end

  def index
    @search = Author.ransack (params[:q])
    @authors = @search.result.alphabet.paginate page: params[:page],per_page: Settings.author.per_page
  end

  def update
    if @author.update_attributes authors_params
      flash[:success] = t ".update_success"
      redirect_to authors_path
    else
      render :edit
    end
  end

  private
  def authors_params
    params.require(:author).permit :name, :description
  end

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "authors.load_author.error_message"
    redirect_to root_path
  end
end

app/views/authors/_author.html.erb
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <tr>
          <td  width="27%"><%=  author.name %></td>
          <td width="30%"><%=  author.description %></td>
          <% if user_signed_in? && current_user.admin? %>
          <td class="text-right">
            <%= link_to t(".delete"), author,
              method: :delete, data: {confirm: t(".confirm")} %>
              | <%= link_to t(".edit"), edit_author_path(author) %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <%= render "shared/error_messages", object: @author%>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/authors/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t (".update_author") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @author do |f| %>
      <%= render "shared/error_messages", object: @author %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t(".edit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/authors/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".title") %></h1><hr>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to new_author_path, class: "btn btn-danger" do %>
    <span class="glyphicon glyphicon-plus">&nbsp;<%= t(".add") %></span>
  <% end %>
<% end %>
<hr>
<div class="input-group search_inline">
  <%= search_form_for  @search, url: authors_path do |f| %>
      <%= f.text_field :name_cont,
        placeholder: t(".search"), class: "form-control search_input" %>
      <%= f.submit t(".button_search"), class: "btn btn-primary btn_search"%>
  <% end %>
</div>
<%= will_paginate %>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th class="text-justify active" width="30%"><%= sort_link(@search, :name, t(".name")) %></th>
          <th class="text-justify active" width="30%"><%= sort_link(@search, :description, t(".description")) %></th>
          <% if user_signed_in? && current_user.admin? %>
            <th class="text-right active"><%= t ".action" %></th>
          <% end %>
        </tr>
      </thead>
    </table>
  </div>
</div>
<ul class="authors">
  <%= render @authors %>
</ul>
<%= will_paginate %>

app/views/authors/new.html.erb
<% provide :title, t(".author") %>
<% provide :button_text, t(".submit") %>
<div class="center jumbotron">
  <h1><%= t(".author") %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/authors/show.js.erb
$('#denyModal').html('<%= j render "books/author" %>');
$('#denyModal').modal('show');