config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  default_url_options host: "localhost:3000"
  root "books#index"
  get "users/show"
  get "users/new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  delete "logout", to: "sessions#destroy"

  resources :users, :authors, :publishers, :books, :categories, :borrows
  resources :borrow_details, only: [:create, :update, :destroy]
  #resource :cart, only: [:show]
  resource :cart
  resources :cart

  namespace :admin do
    resources :books
    resources :borrows do
      member do
        get "accept_request"
        patch "deny_request"
      end
    end
    resources :borrow_details, only: [:create, :update, :destroy]
  end

  resources :books do
    resources :likes
    resources :comments
  end

  resources :users do
    resources :likes
    resources :comments
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  has_many :borrow_details, dependent: :destroy
  has_many :books, through: :borrow_details

  validates :date_borrow, presence: true
  validates :end_date_borrow, presence: true
  #validates :total_book, presence: true,
  #  numericality: {only_integer: true, greater_than: 0}

  enum status: {pending: 0, accept: 1, deny: 2}

  scope :newest, ->{order created_at: :DESC}

  def total_book
    borrow_details.map{|rd| rd.valid? ? rd.number : 0}.sum
  end

  def set_day
    self.date_borrow = Time.current.in_time_zone("Hanoi")
    self.end_date_borrow = from_day + 7.days
  end
end

app/controllers/admin/borrows_controller.rb
class Admin::BorrowsController < ApplicationController
  before_action :load_borrow, except: %i(update index)
  before_action :check_time_borrow, only: %i(update)
  before_action :load_borrow_details, only: %i(index)
  before_action :is_admin?, only: %i(accept_request deny_request)
  before_action :check_quantity, only: %i(accept_request)

  authorize_resource

  def show
    @borrow_details = BorrowDetail.load_borrow_details params[:id]
    return unless @borrow_details.blank?
    flash[:danger] = t ".dont_exist"
    redirect_to root_path
  end

  def edit; end

  def index
    @borrows = Borrow.newest.paginate page: params[:page],
      per_page: Settings.paginate.per_page
    return if @borrows
    flash[:danger] = t (".no_borrow")
    redirect_back fallback_location: root_path
  end

  def update
    if @borrow.update_attributes borrows_params
      flash[:success] = t ".update_success"
      redirect_to @borrow
    else
      render :edit
    end
  end

  def destroy
    if @borrow.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to fallback_location: root_path
  end

  def accept_request
    if @borrow.accept!
      update_quantity
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_back fallback_location: root_path
  end

  def deny_request
    if @borrow.update_attributes deny_borrow_params
      @success = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to admin_borrows_path
  end

  private
  def borrows_params
    params.require(:borrow).permit :note, :date_borrow, :end_date_borrow
  end

  def load_borrow_details
    @borrow_details = BorrowDetail.load_borrow_details params[:id]
  end

  def deny_borrow_params
    params.require(:borrow).permit :note, :status
  end

  def load_borrow
    @borrow = Borrow.find_by id: params[:id]
    return if @borrow
    flash[:danger] = t "borrows.load_borrow.error_message"
    redirect_to root_path
  end

  def check_time_borrow
    return if params[:borrow][:date_borrow] < params[:borrow][:end_date_borrow]
    flash[:danger] = t ".error"
    redirect_to edit_borrow_path
  end

  def check_quantity
    flag = 0
    @borrow.borrow_details.each do |borrow_detail|
      @borrow.books.each do |book|
        if borrow_detail.book_id == book.id && (book.amount -
          borrow_detail.number).negative?
          flag -= 1
        end
      end
    end
    return if flag.zero?
    flash[:danger] = t(".run_out")
    redirect_to borrows_path
  end

  def update_quantity
    @borrow.borrow_details.each do |request_detail|
      @borrow.books.each do |book|
        if request_detail.book_id == book.id
          book.amount -= request_detail.number
          book.update_attribute(:amount, book.amount)
        end
      end
    end
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :load_borrow, only: %i(show edit update destroy)
  before_action :check_time_borrow, only: %i(update)
  before_action :load_borrow_details, only: %i(index)

  authorize_resource

  def create; end

  def show
    @borrow_details = BorrowDetail.load_borrow_details params[:id]
    return unless @borrow_details.blank?
    flash[:danger] = t ".dont_exist"
    redirect_to root_path
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @borrows = Borrow.newest.paginate page: params[:page],
      per_page: Settings.paginate.per_page
    return if @borrows
    flash[:danger] = t (".no_borrow")
    redirect_back fallback_location: root_path
  end

  def update
    if @borrow.update_attributes borrows_params
      flash[:success] = t ".update_success"
      redirect_to @borrow
    else
      render :edit
    end
  end

  def destroy
    if @borrow.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".failed"
    end
    redirect_to borrows_path
  end

  private
  def borrows_params
    params.require(:borrow).permit :note, :date_borrow, :end_date_borrow
  end

  def load_borrow_details
    @borrow_details = BorrowDetail.load_borrow_details params[:id]
  end

  def load_borrow
    @borrow = Borrow.find_by id: params[:id]
    return if @borrow
    flash[:danger] = t "borrows.load_borrow.error_message"
    redirect_to root_path
  end

  def check_time_borrow
    return if params[:borrow][:date_borrow] < params[:borrow][:end_date_borrow]
    flash[:danger] = t ".error"
    redirect_to edit_borrow_path
  end
end

app/helpers/admin/borrows_helper.rb
module Admin::BorrowsHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
  def current_borrow
    borrow = Borrow.find_by id: session[:borrow_id]
    if session[:borrow_id].present? && borrow.present?
      borrow
    elsif user_signed_in?
      @current_user.borrows.new
    else
      Borrow.new
    end
  end
end

app/views/admin/borrows/_borrow.html.erb
<tr>
  <td><%= link_to borrow.id, borrow_path(borrow.id) %></td>
  <td><%= borrow.user.full_name %></td>
  <td><%= l(borrow.date_borrow, format: :short) %></td>
  <td><%= l(borrow.end_date_borrow, format: :short) %></td>
  <td><%= borrow.total_book %></td>
  <td id=<%= "status-borrow-#{borrow.id}" %> class="status"><%= borrow.status %></td>
  <td><%= l(borrow.created_at, format: :short) %></td>
  <td id=<%= "action-borrow-#{borrow.id}" %> >
      <% if borrow.pending? %>
        <%= link_to t(".accept"), accept_request_admin_borrow_path(id: borrow.id), method: :get, data: {confirm: t(".confirm_accept")}, class: "btn btn-success inline" %>
        <%= link_to t(".deny"), edit_admin_borrow_path(id: borrow.id), data: {confirm: t(".confirm_deny")}, class: "btn btn-danger inline"%>
      <% end %>
  </td>
  <td id=<%= "note-borrow-#{borrow.id}" %>><%= borrow.note %></td>
</tr>

app/views/admin/borrows/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".button_confirm") %>
<%= form_for @borrow, url: deny_request_admin_borrow_path, remote: true  do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :note %>
  <%= f.text_area :note, class: "form-control" %>

  <%= f.hidden_field :status, value: :deny %>
  <%= f.hidden_field :id, value: current_borrow.id %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/borrows/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>

<ul class="users">
  <table class="table table-hover request container-fluid">
    <tr class="active">
      <th><%= t(".borrow_id") %></th>
      <th class="name_user"><%= t(".name") %></th>
      <th><%= t(".from") %></th>
      <th><%= t(".to") %></th>
      <th><%= t(".total_book") %></th>
      <th class="_status"><%= t(".status") %></th>
      <th><%= t(".day") %></th>
      <th class="text-center"><%= t(".action") %></th>
      <th class="text-center note"><%= t(".note") %></th>
    </tr>
      <%= render @borrows%>
  </table>
</ul>

<div id="denyModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Reason why you deny?</h4>
      </div>
      <div class="modal-body modal-body-deny-form-request">
      </div>
    </div>
  </div>
</div>